language: generic 
sudo: required
services: 
  - docker
before_install:
  - docker build -t pranav0073/docker -f Dockerfile.dev .
script:
  - docker run -e CI=true pranav0073/docker npm run test -- -- coverage